from src.login import header
import requests
endpoint_notification = "https://api.hypernative.xyz/notification-channels"

notification_response = requests.get(endpoint_notification, headers=header).json()
notification_channels = notification_response["data"]["results"]

channels = [
    {"name": "Guardians Institutional", "dao": "None"},
    {"name": "test-response-kpk-testsafe", "dao": "None"},
    {"name": "Alerts kpk test env", "dao": "None"},
    {"name": "Alerts kpk prod env", "dao": "None"},
    {"name": "[GUARDIANS]Aavev3Hack", "dao": "None"},
    {"name": "[GUARDIANS]MorphoHack", "dao": "None"},
    {"name": "shu_receive_alert", "dao": "None"},
    {"name": "alpha-subscription", "dao": "None"},
    {"name": "Nexus Monitoring", "dao": "Nexus"},
    {"name": "institutional-fund-alerts", "dao": "Institutional"},
    {"name": "treasury-safedao-action", "dao": "SafeDAO"},
    {"name": "treasury-safedao-reminders", "dao": "SafeDAO"},
    {"name": "treasury-safedao-monitoring", "dao": "SafeDAO"},
    {"name": "testingRich", "dao": "None"},
    {"name": "GnosisDAO_GNO_token_alerts", "dao": "GnosisDAO"},
    {"name": "GnosisDAO action", "dao": "GnosisDAO"},
    {"name": "GnosisDAO reminders", "dao": "GnosisDAO"},
    {"name": "Balancer monitoring", "dao": "Balancer"},
    {"name": "ENS reminders", "dao": "ENS"},
    {"name": "kpk monitoring", "dao": "kpk"},
    {"name": "Gnosisltd monitoring", "dao": "GnosisLtd"},
    {"name": "Balancer action", "dao": "Balancer"},
    {"name": "ENS action", "dao": "ENS"},
    {"name": "Cow action", "dao": "Cow"},
    {"name": "Balancer reminders", "dao": "Balancer"},
    {"name": "Cow monitoring", "dao": "Cow"},
    {"name": "Cow reminders", "dao": "Cow"},
    {"name": "kpk action", "dao": "kpk"},
    {"name": "kpk reminders", "dao": "kpk"},
    {"name": "Gnosisltd action", "dao": "GnosisLtd"},
    {"name": "Gnosisltd reminders", "dao": "GnosisLtd"},
    {"name": "GnosisDAO Monitoring", "dao": "GnosisDAO"},
    {"name": "ENS monitoring", "dao": "ENS"},
    {"name": "circles_low_gas", "dao": "Circles"},
    {"name": "Circles_low_gas", "dao": "Circles"},
    {"name": "COW_transfer_alert", "dao": "Cow"},
    {"name": "USDCe_Alert", "dao": "None"},
    {"name": "GnosisDAO_USDCe_alerts", "dao": "GnosisDAO"},
    {"name": "treasury-aave-reminders", "dao": "Aave"},
    {"name": "treasury-aave-monitoring", "dao": "Aave"},
    {"name": "treasury-aave-action", "dao": "Aave"},
    {"name": "riskpositions-database-channel", "dao": "None"},
    {"name": "hyp-alerts-dai-usdc-usdt", "dao": "None"},
    {"name": "Telegram-1", "dao": "None"},
]